[2024-08-14T01:35:41.828+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T01:35:41.856+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl_pipeline.reddit_data_extraction manual__2024-08-14T01:35:39.836772+00:00 [queued]>
[2024-08-14T01:35:41.866+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl_pipeline.reddit_data_extraction manual__2024-08-14T01:35:39.836772+00:00 [queued]>
[2024-08-14T01:35:41.867+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T01:35:41.881+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): reddit_data_extraction> on 2024-08-14 01:35:39.836772+00:00
[2024-08-14T01:35:41.887+0000] {standard_task_runner.py:64} INFO - Started process 54 to run task
[2024-08-14T01:35:41.948+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl_pipeline', 'reddit_data_extraction', 'manual__2024-08-14T01:35:39.836772+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/rdt_dags.py', '--cfg-path', '/tmp/tmpiggeocqk']
[2024-08-14T01:35:41.999+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask reddit_data_extraction
[2024-08-14T01:35:42.467+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl_pipeline.reddit_data_extraction manual__2024-08-14T01:35:39.836772+00:00 [running]> on host 3dd0aebc6153
[2024-08-14T01:35:42.738+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ROmin Katre' AIRFLOW_CTX_DAG_ID='reddit_etl_pipeline' AIRFLOW_CTX_TASK_ID='reddit_data_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T01:35:39.836772+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T01:35:39.836772+00:00'
[2024-08-14T01:35:42.747+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T01:35:42.813+0000] {logging_mixin.py:188} INFO - Connected to Rddit successfully
[2024-08-14T01:35:43.324+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T01:35:43.327+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 10, in reddit_pipeline
    post_df = pd.DateFrame(posts)
AttributeError: module 'pandas' has no attribute 'DateFrame'
[2024-08-14T01:35:43.366+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=reddit_etl_pipeline, task_id=reddit_data_extraction, run_id=manual__2024-08-14T01:35:39.836772+00:00, execution_date=20240814T013539, start_date=20240814T013541, end_date=20240814T013543
[2024-08-14T01:35:43.389+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task reddit_data_extraction (module 'pandas' has no attribute 'DateFrame'; 54)
[2024-08-14T01:35:43.422+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-14T01:35:43.445+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-14T01:35:43.447+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
